{% set version = "0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tufte
  version: {{ version|replace("-", "_") }}

source:
  fn: tufte_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tufte_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tufte/tufte_{{ version }}.tar.gz
  sha256: 72cb935e13ec8229182b5660079745ca828169165e239b1445d89399adad7134

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-knitr >=1.18
    - r-rmarkdown
    - r-xfun
  run:
    - r-base
    - r-htmltools
    - r-knitr >=1.18
    - r-rmarkdown
    - r-xfun

test:
  commands:
    - $R -e "library('tufte')"           # [not win]
    - "\"%R%\" -e \"library('tufte')\""  # [win]

about:
  home: https://github.com/rstudio/tufte
  license: GPL-3
  summary: Provides R Markdown output formats to use Tufte styles for PDF and HTML output.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
