{% set version = "0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tufte
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tufte_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tufte/tufte_{{ version }}.tar.gz
  sha256: 70d3f9252a37393f732b5d043c75f1a5354540121507a00fa2eccf0a6e05dde3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-knitr >=1.28
    - r-rmarkdown >=2.1
    - r-xfun >=0.13
  run:
    - r-base
    - r-htmltools
    - r-knitr >=1.28
    - r-rmarkdown >=2.1
    - r-xfun >=0.13

test:
  commands:
    - $R -e "library('tufte')"           # [not win]
    - "\"%R%\" -e \"library('tufte')\""  # [win]

about:
  home: https://github.com/rstudio/tufte
  license: GPL-3.0-only
  summary: Provides R Markdown output formats to use Tufte styles for PDF and HTML output.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tufte
# Type: Package
# Title: Tufte's Styles for R Markdown Documents
# Version: 0.5
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("JJ", "Allaire", role = "aut"), person("Andrzej", "Oles", role = "ctb"), person("Dave", "Liepmann", role = "ctb", comment = "Tufte CSS in inst/rmarkdown/templates/tufte_html/resources"), person(family = "RStudio, Inc.", role = "cph") )
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Provides R Markdown output formats to use Tufte styles for PDF and HTML output.
# License: GPL-3
# LazyData: TRUE
# URL: https://github.com/rstudio/tufte
# BugReports: https://github.com/rstudio/tufte/issues
# Imports: htmltools, xfun (>= 0.6), knitr (>= 1.22), rmarkdown (>= 1.12)
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-12 00:49:49 UTC; yihui
# Author: Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), JJ Allaire [aut], Andrzej Oles [ctb], Dave Liepmann [ctb] (Tufte CSS in inst/rmarkdown/templates/tufte_html/resources), RStudio, Inc. [cph]
# Repository: CRAN
# Date/Publication: 2019-05-12 05:00:03 UTC
